import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import starIcon from '@/assets/images/Star.png';
import { Link } from 'react-router-dom';
import { BsArrowRight } from 'react-icons/bs';
const DoctorCard = ({ doctor }) => {
    const { name, avgRating, totalRating, photo, specialization, totalPatients, hospital, } = doctor;
    return (_jsxs("div", { className: 'p-3 lg:p-5', children: [_jsx("div", { children: _jsx("img", { src: photo, alt: 'doctor specialization', className: 'w-full rounded' }) }), _jsx("h2", { className: 'text-[18px] leading-[30px] lg:text-[22px] lg:leading-9 text-headingColor font-[700] mt-3 lg:mt-5 ', children: name }), _jsxs("div", { className: 'mt-2 lg:mt-4 flex items-center justify-between ', children: [_jsx("span", { className: 'bg-[#CCF0F3] text-irisBlueColor py-1 px-2 lg:py-2 lg:px-6 text-[12px] leading-4 lg:text-[16px] rounded lg:leading-7 font-semibold ', children: specialization }), _jsxs("div", { className: 'flex items-center gap-[6px]', children: [_jsxs("span", { className: 'flex items-center gap-[6px] text-[14px] leading-6 lg:text-[16px] lg:leading-7 font-semibold text-headingColor ', children: [_jsx("img", { src: starIcon, alt: 'doctors app' }), " ", avgRating] }), _jsxs("span", { className: 'text-[14px] leading-6 lg:text-[16px] lg:leading-7 font-[400] text-textColor ', children: [totalRating, ' '] })] })] }), _jsxs("div", { className: 'mt-[18px] lg:mt-5 flex items-center justify-between ', children: [_jsxs("div", { children: [_jsxs("h3", { className: 'text-[16px] leading-7 lg:text-[18px]  ', children: ["+", totalPatients, " patients"] }), _jsxs("p", { className: 'text-[13px] lg:text-[15] leading-6 font-[400] text-textColor ', children: ["At ", hospital] })] }), _jsx(Link, { to: '/doctors', className: 'w-[44px] h-[44px] rounded-full border border-solid border-[#181A1E] flex items-center justify-center group hover:bg-primaryColor hover:border-none', children: _jsx(BsArrowRight, { className: 'group-hover:text-white w-6 h-5' }) })] })] }));
};
export default DoctorCard;
