import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import logo from '@/assets/images/logo.png';
import { socialLinks, quickLink01, quickLinks02, quickLinks03, } from '@/components/quick-links';
const Footer = () => {
    const year = new Date().getFullYear();
    return (_jsx("footer", { className: 'pb-16 pt-10', children: _jsx("div", { className: 'container', children: _jsxs("div", { className: 'flex justify-between flex-col md:flex-row flex-wrap gap-[35px]', children: [_jsxs("div", { children: [_jsx("img", { src: logo, alt: 'doctors image' }), _jsxs("p", { className: 'text-[15px] leading-7 font-[400] text-textColor mt-6 ', children: ["Copyright \u00A9 ", year, " | developed by Enaholo Akhere | all rights reserved."] }), _jsx("div", { className: 'flex items-center gap-3 mt-4', children: socialLinks.map((socials, index) => (_jsx(Link, { to: socials.path, className: 'w-9 h-9 border border-solid border-[#1B1A1E] rounded-full flex items-center justify-center group hover:bg-primaryColor hover:border-none ', children: socials.icon }, index + 'social-link'))) })] }), _jsxs("div", { children: [_jsx("h2", { className: 'text-[20px] leading-[30px] font-[700] mb-6 text-headingColor ', children: "Quick Links" }), _jsx("ul", { children: quickLink01.map((qLink, index) => (_jsx("li", { className: 'mb-4', children: _jsx(Link, { to: qLink.path, className: 'text-[15px] leading-7 font-[400] text-textColor ', children: qLink.display }) }, index + 'quick-link'))) })] }), _jsxs("div", { children: [_jsx("h2", { className: 'text-[20px] leading-[30px] font-[700] mb-6 text-headingColor ', children: "I want to:" }), _jsx("ul", { children: quickLinks02.map((qLink, index) => (_jsx("li", { className: 'mb-4', children: _jsx(Link, { to: qLink.path, className: 'text-[15px] leading-7 font-[400] text-textColor ', children: qLink.display }) }, index + 'quick-link'))) })] }), _jsxs("div", { children: [_jsx("h2", { className: 'text-[20px] leading-[30px] font-[700] mb-6 text-headingColor ', children: "Support" }), _jsx("ul", { children: quickLinks03.map((qLink, index) => (_jsx("li", { className: 'mb-4', children: _jsx(Link, { to: qLink.path, className: 'text-[15px] leading-7 font-[400] text-textColor ', children: qLink.display }) }, index + 'quick-link'))) })] })] }) }) }));
};
export default Footer;
